### ISSUE TITLE
Unable to access the website to download the application

### ISSUE THREAD

**Issue by asylumexp** [Molay/LaunchPadder#2]
![image](https://user-images.githubusercontent.com/54530346/167993068-d60aba94-e0cf-46c8-871b-a5e59889fdcd.png)
Unable to access website (See image above)

**Comment by Molay** [comment]
My website is currently using Alibaba Cloud. Maybe the network segment of Alibaba Cloud is blocked by your ISP or DNS.
To avoid further inconvenience, from now on, I will publish new versions and information on github synchronously.
Please check this link: https://github.com/Molay/LaunchPadder/releases
Thanks for your feedback :)

**Comment by asylumexp** [comment]
Thanks!
